# Generated by Django 3.2.9 on 2021-11-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=200, verbose_name='Colección')),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_nickname', models.CharField(max_length=200, verbose_name='Nickname')),
            ],
            options={
                'verbose_name': 'Creador',
                'verbose_name_plural': 'Creadores',
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_contract_addr', models.CharField(max_length=256, verbose_name='Contract Address')),
                ('nft_name', models.CharField(max_length=200, verbose_name='Token Name')),
                ('nft_id', models.CharField(blank=True, max_length=5, verbose_name='Token Id')),
                ('nft_standard', models.CharField(max_length=10, verbose_name='Token Standard')),
                ('nft_blockchain', models.CharField(max_length=100, verbose_name='Blockchain')),
                ('collection_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.collection', verbose_name='Colección')),
                ('creator', models.ManyToManyField(to='marketplace.Creator', verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'NFT',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='token',
            field=models.ManyToManyField(to='marketplace.NFT', verbose_name='NFT'),
        ),
    ]
