# Generated by Django 3.2.9 on 2021-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='token',
            field=models.ManyToManyField(null=True, to='marketplace.NFT', verbose_name='NFT'),
        ),
    ]
