# Generated by Django 3.2.9 on 2021-11-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_collection_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='token',
            field=models.ManyToManyField(to='marketplace.NFT', verbose_name='NFT'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='collection_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.collection', verbose_name='Colección'),
        ),
    ]
