# Generated by Django 3.2.9 on 2021-11-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20211129_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='author_nickname',
            new_name='creator_nickname',
        ),
    ]
