# Generated by Django 3.2.9 on 2021-11-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_rename_author_nickname_creator_creator_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nft',
            options={'ordering': ['nft_contract_addr'], 'verbose_name': 'NFT'},
        ),
    ]
