# Generated by Django 3.2.9 on 2021-11-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_nft_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='token',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='creator',
        ),
        migrations.AddField(
            model_name='collection',
            name='nfts',
            field=models.ManyToManyField(related_name='nfts', to='marketplace.NFT', verbose_name='NFT'),
        ),
        migrations.AddField(
            model_name='nft',
            name='creators',
            field=models.ManyToManyField(related_name='creators', to='marketplace.Creator', verbose_name='Creador'),
        ),
    ]
