# Generated by Django 3.2.9 on 2021-11-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20211129_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='nfts',
            field=models.ManyToManyField(to='marketplace.NFT', verbose_name='NFT'),
        ),
    ]
