# Generated by Django 3.2.9 on 2021-11-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20211130_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='creators',
        ),
        migrations.AddField(
            model_name='nft',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creators', to='marketplace.creator', verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='nft_id',
            field=models.CharField(max_length=5, verbose_name='Token Id'),
        ),
    ]
