# Generated by Django 3.2.9 on 2021-12-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20211206_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='creators',
            field=models.ManyToManyField(related_name='creators', to='marketplace.Creator'),
        ),
    ]
