# Generated by Django 3.2.9 on 2021-12-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_nft_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='creators',
        ),
        migrations.AddField(
            model_name='nft',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creators', to='marketplace.creator', verbose_name='Creador'),
        ),
    ]
