# Generated by Django 3.2.9 on 2021-12-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20211206_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='creator',
            new_name='creators',
        ),
    ]
