# Generated by Django 3.2.9 on 2021-12-09 18:59

from django.db import migrations, models
import django.db.models.deletion
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_auto_20211207_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_image',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.Collection.collection_upload_img_url, verbose_name="Collection's image"),
        ),
        migrations.AddField(
            model_name='nft',
            name='nft_image',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.NFT.nft_upload_img_url, verbose_name="NFT's image"),
        ),
        migrations.AlterField(
            model_name='nft',
            name='collection_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.collection'),
        ),
    ]
