# Generated by Django 3.2.9 on 2021-12-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='nft_price_crypto',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='ETH Price'),
        ),
        migrations.AddField(
            model_name='nft',
            name='nft_price_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Dollar Price'),
        ),
    ]
