# Generated by Django 3.2.9 on 2021-12-10 18:41

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_remove_nft_nft_price_dollar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='nfts',
            field=models.ManyToManyField(related_name='nfts_collection', to='marketplace.NFT', verbose_name='NFT'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='nft_image',
            field=models.ImageField(max_length=256, upload_to=marketplace.models.NFT.nft_upload_img_url, verbose_name="NFT's image"),
        ),
        migrations.AlterField(
            model_name='nft',
            name='nft_price_crypto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ETH Price'),
        ),
    ]
