# Generated by Django 3.2.9 on 2021-12-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_auto_20211210_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='creators',
        ),
        migrations.AddField(
            model_name='nft',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='marketplace.creator'),
        ),
    ]
